currencyconvecter/convert/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Main.as_view(), name='home'),
    path('currency/', Currency.as_view(), name='currency'),
    path('converter/', Converter.as_view(), name='converter'),
]

currencyconvecter/currencyconvecter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('convert.urls')),
]

currencyconvecter/convert/models.py
from django.db import models

# Create your models here.

currencyconvecter/convert/forms.py
from django import forms

class CurrencyForm(forms.Form):
    amount = forms.IntegerField()
    currency_from = forms.CharField(label='currency_from')
    currency_to = forms.CharField(label='currency_to')

currencyconvecter/convert/views.py
from django.shortcuts import render
import requests
from xml.dom import minidom
from  django.views.generic import View

from .forms import CurrencyForm

def get_currency_dictionary_with_date(url):
    response = requests.get(url)

    dom = minidom.parseString(response.text)
    dom.normalize()

    response_date = dom.firstChild.getAttribute("Date")
    elements = dom.getElementsByTagName("Valute")
    currency_dict = {}

    for node in elements:
        for child in node.childNodes:
            if child.nodeType == 1:
                if child.tagName == 'Value':
                    if child.firstChild.nodeType == 3:
                        value = child.firstChild.data
                if child.tagName == 'CharCode':
                    if child.firstChild.nodeType == 3:
                        char_code = child.firstChild.data
        currency_dict[char_code] = value
    return currency_dict, response_date


class Main(View):
    def get(self, request):
        return render(request, 'convert/index.html')


class Currency(View):
    def get(self, request):
        url = 'https://cbr.ru/scripts/XML_daily.asp'
        currency_dict, response_date = get_currency_dictionary_with_date(url)
        return render(request, 'convert/currency.html', {'response': currency_dict, 'date': response_date})


class Converter(View):


    def post(self, request):
        url = 'https://cbr.ru/scripts/XML_daily.asp'
        form = CurrencyForm(request.POST)
        if form.is_valid():
            char_code_to = form.cleaned_data['currency_to']
            char_code_from = form.cleaned_data['currency_from']
            amount = form.cleaned_data['amount']

            currency_dict, response_date = get_currency_dictionary_with_date(url)
            currency_value_to = float(currency_dict[char_code_to].replace(',', '.'))
            currency_value_from = float(currency_dict[char_code_from].replace(',', '.'))

            currency_converted = round(currency_value_from / currency_value_to * amount, 2)

            return render(request, 'convert/convert.html', {'form': form, 'currency_converted': currency_converted})

    def get(self, request):
        url = 'https://cbr.ru/scripts/XML_daily.asp'
        currency_dict, response_date = get_currency_dictionary_with_date(url)
        char_codes = currency_dict.keys()
        form = CurrencyForm()

        return render(request, 'convert/convert.html', {'char_codes': char_codes, 'form': form})

currencyconvecter/convert/templates/convert/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <div>
         <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
             <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'home' %}">Главная</a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'currency' %}">Курс валюты</a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'converter' %}">Обменник</a>
        </nav>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

currencyconvecter/convert/templates/convert/convert.html
{% extends 'convert\base.html' %}

{% block title %}
Обменник
{% endblock %}

{% block content %}


    {% if currency_converted %}
        <h4>
           Конвертация {{form.amount.value}} {{form.currency_from.value}}
            составляет {{currency_converted}} {{form.currency_to.value}}
        </h4>

    {% else %}
        <h4> Выберите валюты для обмена</h4>
        <form action="{% url 'converter' %}" method="post">
         {% csrf_token %}
        <p><label for="id_amount">Amount:</label>
            <input type="number" step="1" min="1" max="1000000" value="10"name="amount" required id="id_amount"/>
        </p>

         <p><label for="id_currency_from">currency_from:</label>
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg" name="currency_from" required id="id_currency_from">
                {% for char_code in char_codes %}
                    <option selected>{{ char_code }} </option>
                {% endfor %}
            </select>
        </p>
        <p><label for="id_currency_to">currency_to:</label>
             <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg "name="currency_to" required id="id_currency_to">
                {% for char_code in char_codes %}
                      <option value={{ char_code }} selected>{{ char_code }} </option>
                {% endfor %}
             </select>
         </p>
        <p>
            <button  type="submit" id="submit">Отправить</button>
        </p>
    </form>
 {% endif %}


    <!--<script>
        let select1 = document.getElementById("cur1");
        let select2 = document.getElementById("cur2");

        document.querySelector('#submit').onclick = function() {
            let idx = select1.selectedIndex;
            let cur1 = select1.options[idx].value;
            idx = select2.selectedIndex;
            let cur2 = select2.options[idx].value;

         }
    </script>
-->
{% endblock %}

currencyconvecter/convert/templates/convert/currency.html
{% extends 'convert\base.html' %}

{% block title %}
    Официальные курсы валют
{% endblock %}

{% block content %}
    <h1>Официальный курс рубля на {{ date }}</h1>
    {% for key, value in response.items %}
        <div class="alert alert-warning mt-2">
            <h3>{{ key }} -> {{ value }}</h3>
        </div>
    {% endfor %}

{% endblock %}

currencyconvecter/convert/templates/convert/index.html
{% extends 'convert\base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    <h2>Тестовое задание</h2>
{% endblock %}